services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    environment:
      NAME: $SAMBA_NAME
      USER: $SAMBA_USER
      PASS: $SAMBA_PASS
    ports:
      - 445:445
    volumes:
      - /mnt/hitachi/samba:/storage
    restart: always
