services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
      - /media/rpi/hitachi:/hitachi
    environment:
      HOMEPAGE_ALLOWED_HOSTS: raspberrypi.local:3000,192.168.0.20:3000,homepage.rpi # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_USERNAME: $HOMEPAGE_VAR_USERNAME
      HOMEPAGE_VAR_PASSWORD: $HOMEPAGE_VAR_PASSWORD
      HOMEPAGE_VAR_USERNAME_WIREGUARD: $HOMEPAGE_VAR_USERNAME_WIREGUARD
      HOMEPAGE_VAR_PASSWORD_WIREGUARD: $HOMEPAGE_VAR_PASSWORD_WIREGUARD
      HOMEPAGE_VAR_KEY_PORTAINER: $HOMEPAGE_VAR_KEY_PORTAINER
      HOMEPAGE_VAR_KEY_PIHOLE: $HOMEPAGE_VAR_KEY_PIHOLE
      HOMEPAGE_VAR_KEY_PLEX: $HOMEPAGE_VAR_KEY_PLEX
      HOMEPAGE_VAR_KEY_HOMEASSISTANT: $HOMEPAGE_VAR_KEY_HOMEASSISTANT
      HOMEPAGE_VAR_KEY_IMMICH: $HOMEPAGE_VAR_KEY_IMMICH
