services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=Europe/Belgrade
      - WATCHTOWER_SCHEDULE=0 0 12 * * 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

