---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Containers:
    - Portainer:
        href: https://portainer.rpi
        description: obzerve dem containerz
        icon: portainer.svg
        widget:
          type: portainer
          url: https://192.168.0.20:9443
          env: 3
          kubernetes: false
          key: {{HOMEPAGE_VAR_KEY_PORTAINER}}

- Network:
    - Pi-Hole:
        href: https://pihole.rpi/admin
        description: block dem adz
        icon: pi-hole.svg
        widget:
          type: pihole
          url: http://pihole
          version: 6
          key: {{HOMEPAGE_VAR_KEY_PIHOLE}}
    - Wireguard:
        href: https://wireguard.rpi
        description: tunnel dem trafficz
        icon: wireguard.svg
        widget:
          type: wgeasy
          url: http://192.168.0.20:51821
          version: 2
          username: {{HOMEPAGE_VAR_USERNAME_WIREGUARD}}
          password: {{HOMEPAGE_VAR_PASSWORD_WIREGUARD}}
          threshold: 2 # optional

- Media:
    - Plex:
        href: https://plex.rpi
        description: watch dem moviez & tvshowz
        icon: plex.png
        widget:
          type: plex
          url: http://192.168.0.20:32400
          key: {{HOMEPAGE_VAR_KEY_PLEX}}
    - Immich:
        href: https://immich.rpi
        description: host dem photoz
        icon: immich.svg
        widget:
          type: immich
          url: http://192.168.0.20:2283
          key: {{HOMEPAGE_VAR_KEY_IMMICH}}
          version: 2 # optional

- IoT:
    - Home Assistant:
        href: http://192.168.0.20:8123
        description: smart dem homez
        icon: home-assistant-alt.svg

- Download:
    - qBittorrent:
        href: https://qbittorrent.rpi
        description: download dem torrentz
        icon: qbittorrent.svg
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://192.168.0.20:8080
          username: {{HOMEPAGE_VAR_USERNAME}}
          password: {{HOMEPAGE_VAR_PASSWORD}}
