---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

#layout:
#  Media:
#    icon: mdi-play-network-#FFFFFF
