---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background: https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1374

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

#layout:
#  Media:
#    icon: mdi-play-network-#FFFFFF
